
export const demoCategories = [
  {
    id: '1',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Latest gadgets and electronics',
    image_url: '/placeholder-category.jpg',
    parent_id: null,
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Fashion',
    slug: 'fashion',
    description: 'Trendy clothing and accessories',
    image_url: '/placeholder-category.jpg',
    parent_id: null,
    is_active: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Home & Garden',
    slug: 'home-garden',
    description: 'Everything for your home and garden',
    image_url: '/placeholder-category.jpg',
    parent_id: null,
    is_active: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoProducts = [
  {
    id: '1',
    seller_id: 'demo-seller',
    category_id: '1',
    name: 'Wireless Bluetooth Headphones',
    slug: 'wireless-bluetooth-headphones',
    description: 'High-quality wireless headphones with noise cancellation',
    short_description: 'Premium wireless headphones',
    price: 99.99,
    compare_price: 149.99,
    cost_price: 50.00,
    stock_quantity: 25,
    low_stock_threshold: 5,
    sku: 'WBH-001',
    barcode: '1234567890123',
    weight_kg: 0.3,
    dimensions_cm: '20x15x8',
    status: 'active' as const,
    is_featured: true,
    is_bestseller: false,
    meta_title: 'Wireless Bluetooth Headphones - LuxiorMall',
    meta_description: 'Shop premium wireless bluetooth headphones with noise cancellation',
    tags: ['wireless', 'bluetooth', 'headphones', 'audio'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: '1',
        product_id: '1',
        image_url: '/placeholder-product.jpg',
        alt_text: 'Wireless Bluetooth Headphones',
        is_primary: true,
        sort_order: 1,
        created_at: new Date().toISOString(),
      }
    ],
    variants: [],
    category: demoCategories[0],
  },
  {
    id: '2',
    seller_id: 'demo-seller',
    category_id: '2',
    name: 'Cotton T-Shirt',
    slug: 'cotton-t-shirt',
    description: 'Comfortable 100% cotton t-shirt in various colors',
    short_description: '100% cotton t-shirt',
    price: 19.99,
    compare_price: 29.99,
    cost_price: 8.00,
    stock_quantity: 50,
    low_stock_threshold: 10,
    sku: 'CTS-001',
    barcode: '1234567890124',
    weight_kg: 0.2,
    dimensions_cm: '30x40x2',
    status: 'active' as const,
    is_featured: true,
    is_bestseller: true,
    meta_title: 'Cotton T-Shirt - LuxiorMall',
    meta_description: 'Shop comfortable 100% cotton t-shirts in various colors',
    tags: ['cotton', 't-shirt', 'clothing', 'fashion'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: '2',
        product_id: '2',
        image_url: '/placeholder-product.jpg',
        alt_text: 'Cotton T-Shirt',
        is_primary: true,
        sort_order: 1,
        created_at: new Date().toISOString(),
      }
    ],
    variants: [],
    category: demoCategories[1],
  },
];
